import { clsx } from "clsx";
import { twMerge } from "tailwind-merge";
import { Coins, Crown, Users, Wallet } from "lucide-react";

export function cn(...inputs) {
  return twMerge(clsx(inputs));
}

export const baseImageUrl = "http://localhost:8080/uploads/";

export const data = [
  {
    id: 1,
    fullName: "ABCD",
    title: "Менеджер",
    personalPartners: "0 ta",
    activeRange: "1 Month",
    lowNumberOfNetworkUsers: "15",
    bonusAmount: "Саъхат",
  },
  {
    id: 2,
    fullName: "ABCD",
    title: "Бронза",
    personalPartners: "3 ta",
    activeRange: "2 Month",
    lowNumberOfNetworkUsers: "50",
    bonusAmount: "Оилавий саёхат",
  },
  {
    id: 3,
    fullName: "ABCD",
    title: "Серебро",
    personalPartners: "5 ta",
    activeRange: "3 Month",
    lowNumberOfNetworkUsers: "150",
    bonusAmount: "10000 $",
  },
  {
    id: 4,
    fullName: "ABCD",
    title: "Золото",
    personalPartners: "3 ta Менеджер",
    activeRange: "3 Month",
    lowNumberOfNetworkUsers: "300",
    bonusAmount: "20000 $",
  },
  {
    id: 5,
    fullName: "ABCD",
    title: "Платина",
    personalPartners: "2 ta Бронза",
    activeRange: "4 Month",
    lowNumberOfNetworkUsers: "500",
    bonusAmount: "50000 $",
  },
  {
    id: 6,
    fullName: "ABCD",
    title: "Рубин",
    personalPartners: "4 ta Серебро",
    activeRange: "4 Month",
    lowNumberOfNetworkUsers: "1500",
    bonusAmount: "100000 $",
  },
  {
    id: 7,
    fullName: "ABCD",
    title: "Изумруд",
    personalPartners: "3 ta Золото",
    activeRange: "5 Month",
    lowNumberOfNetworkUsers: "3000",
    bonusAmount: "250000 $",
  },
  {
    id: 8,
    fullName: "ABCD",
    title: "Бриллиант",
    personalPartners: "4 ta Платина",
    activeRange: "6 Month",
    lowNumberOfNetworkUsers: "5000",
    bonusAmount: "500000 $",
  },
  {
    id: 9,
    fullName: "ABCD",
    title: "Мерос",
    personalPartners: "4 ta Изумруд",
    activeRange: "6 Month",
    lowNumberOfNetworkUsers: "10000",
    bonusAmount: "1000000 $",
  },
];

// mockData.js
export const mockCardDataa = [
  {
    id: 1,
    title: "Umumiy Foydalanuvchilar",
    value: "12345",
    icon: <Wallet className="w-5 h-5" />,
    backgroundColor: "bg-blue-500",
  },
  {
    id: 2,
    title: "Aktiv Foydalanuvchilar soni",
    value: "12345",
    icon: <Users className="w-5 h-5" />,
    backgroundColor: "bg-green-500",
  },
  {
    id: 3,
    title: "NoAktiv Foydalanuvchilar soni",
    value: "12345",
    icon: <Coins className="w-5 h-5" />,
    backgroundColor: "bg-purple-500",
  },
];

export const usersData = [
  {
    id: "1",
    first_name: "John",
    last_name: "Doe",
    phone_number: "+1234567890",
    role: "user",
    third_name: "Smith",
    inn: "123456789012",
    email: "john.doe@example.com",
    password: "securepassword123",
    sponsor_id: "someSponsorId",
    parent_id: null,
    passport: "ABC1234567",
    passport_issued: "2024-01-01T00:00:00Z",
    passport_whom_by: "Some Authority",
    left_id: null,
    right_id: null,
    parents: [],
    children: [],
    country: "Uzbekistan",
    degree_id: null,
    register_id: "UZ1234567",
    is_active: true,
    left_pv: 0,
    right_pv: 0,
    mb: 0,
    balance: 1000,
  },
  {
    id: "2",
    first_name: "Alice",
    last_name: "Johnson",
    phone_number: "+9876543210",
    role: "user",
    third_name: "Brown",
    inn: "987654321098",
    email: "alice.johnson@example.com",
    password: "securepassword456",
    sponsor_id: "someOtherSponsorId",
    parent_id: null,
    passport: "XYZ9876543",
    passport_issued: "2023-06-15T00:00:00Z",
    passport_whom_by: "Another Authority",
    left_id: null,
    right_id: null,
    parents: [],
    children: [],
    country: "Uzbekistan",
    degree_id: null,
    register_id: "UZ7654321",
    is_active: false,
    left_pv: 10,
    right_pv: 15,
    mb: 20,
    balance: 500,
  },
  {
    id: "3",
    first_name: "Nodira",
    last_name: "Shonazarova",
    phone_number: "+1234567801",
    role: "admin",
    third_name: "Shonazarova",
    inn: "123987654321",
    email: "nodira.shonazarova@example.com",
    password: "adminpassword123",
    sponsor_id: "adminSponsorId",
    parent_id: null,
    passport: "LMN4567890",
    passport_issued: "2022-09-30T00:00:00Z",
    passport_whom_by: "Admin Authority",
    left_id: null,
    right_id: null,
    parents: [],
    children: [],
    country: "Uzbekistan",
    degree_id: null,
    register_id: "UZ9876543",
    is_active: true,
    left_pv: 50,
    right_pv: 30,
    mb: 40,
    balance: 1500,
  },
  {
    id: "4",
    first_name: "XJ",
    last_name: "Business",
    phone_number: "+1987654321",
    role: "user",
    third_name: "XJ",
    inn: "987123456789",
    email: "xj.business@example.com",
    password: "xjpassword123",
    sponsor_id: "xjSponsorId",
    parent_id: null,
    passport: "OPQ1234567",
    passport_issued: "2021-02-20T00:00:00Z",
    passport_whom_by: "XJ Authority",
    left_id: null,
    right_id: null,
    parents: [],
    children: [],
    country: "Uzbekistan",
    degree_id: null,
    register_id: "UZ0987654",
    is_active: true,
    left_pv: 100,
    right_pv: 50,
    mb: 200,
    balance: 2000,
  },
];

export const dataa = [
  {
    id: 1,
    fullName: "ABCD",
    title: "Менеджер",
    personalPartners: "0 ta",
    activeRange: "1 Month",
    lowNumberOfNetworkUsers: "15",
    bonusAmount: "Саъхат",
  },
  {
    id: 2,
    fullName: "ABCD",
    title: "Бронза",
    personalPartners: "3 ta",
    activeRange: "2 Month",
    lowNumberOfNetworkUsers: "50",
    bonusAmount: "Оилавий саёхат",
  },
  {
    id: 3,
    fullName: "ABCD",
    title: "Серебро",
    personalPartners: "5 ta",
    activeRange: "3 Month",
    lowNumberOfNetworkUsers: "150",
    bonusAmount: "10000 $",
  },
  {
    id: 4,
    fullName: "ABCD",
    title: "Золото",
    personalPartners: "3 ta Менеджер",
    activeRange: "3 Month",
    lowNumberOfNetworkUsers: "300",
    bonusAmount: "20000 $",
  },
  {
    id: 5,
    fullName: "ABCD",
    title: "Платина",
    personalPartners: "2 ta Бронза",
    activeRange: "4 Month",
    lowNumberOfNetworkUsers: "500",
    bonusAmount: "50000 $",
  },
  {
    id: 6,
    fullName: "ABCD",
    title: "Рубин",
    personalPartners: "4 ta Серебро",
    activeRange: "4 Month",
    lowNumberOfNetworkUsers: "1500",
    bonusAmount: "100000 $",
  },
  {
    id: 7,
    fullName: "ABCD",
    title: "Изумруд",
    personalPartners: "3 ta Золото",
    activeRange: "5 Month",
    lowNumberOfNetworkUsers: "3000",
    bonusAmount: "250000 $",
  },
  {
    id: 8,
    fullName: "ABCD",
    title: "Бриллиант",
    personalPartners: "4 ta Платина",
    activeRange: "6 Month",
    lowNumberOfNetworkUsers: "5000",
    bonusAmount: "500000 $",
  },
  {
    id: 9,
    fullName: "ABCD",
    title: "Мерос",
    personalPartners: "4 ta Изумруд",
    activeRange: "6 Month",
    lowNumberOfNetworkUsers: "10000",
    bonusAmount: "1000000 $",
  },
];

export const mockData = [
  {
    id: 1,
    fullName: "Admin Admin",
    userId: "0000000",
    title: "Boshlang'ich",
    balance: 0,
    status: "Active",
    registerDate: "2023-03-08 13:48:50",
    paymentTime: "2025-01-05",
  },
  {
    id: 2,
    fullName: "Test teste",
    userId: "0000203",
    title: "Boshlang'ich",
    balance: 0,
    status: "Active",
    registerDate: "2023-05-04 11:32:42",
    paymentTime: "2023-05-22",
  },
  {
    id: 3,
    fullName: "teste teset",
    userId: "0000204",
    title: "Boshlang'ich",
    balance: 0,
    status: "Active",
    registerDate: "2023-05-04 12:18:07",
    paymentTime: "2023-05-22",
  },
  {
    id: 4,
    fullName: "askldaslkd aslkdmaslkd",
    userId: "0000332",
    title: "Boshlang'ich",
    balance: 0,
    status: "None",
    registerDate: "2023-06-16 18:57:13",
    paymentTime: "2023-06-16",
  },
  {
    id: 5,
    fullName: "Maria Ivanova",
    userId: "0000501",
    title: "Senior",
    balance: 200,
    status: "Active",
    registerDate: "2023-07-01 10:00:00",
    paymentTime: "2023-07-05",
  },
  {
    id: 6,
    fullName: "John Doe",
    userId: "0000510",
    title: "Manager",
    balance: 1500,
    status: "Active",
    registerDate: "2023-08-10 09:20:30",
    paymentTime: "2023-08-15",
  },
  {
    id: 7,
    fullName: "Samantha Green",
    userId: "0000545",
    title: "Consultant",
    balance: 700,
    status: "Active",
    registerDate: "2023-09-12 16:45:22",
    paymentTime: "2023-09-20",
  },
  {
    id: 8,
    fullName: "Dmitry Petrov",
    userId: "0000801",
    title: "Assistant",
    balance: 350,
    status: "Active",
    registerDate: "2023-10-05 08:12:40",
    paymentTime: "2023-10-12",
  },
  {
    id: 9,
    fullName: "Olga Smirnova",
    userId: "0000912",
    title: "Developer",
    balance: 1800,
    status: "Active",
    registerDate: "2023-11-15 14:22:30",
    paymentTime: "2023-11-25",
  },
  {
    id: 10,
    fullName: "Petr Ivanov",
    userId: "0001015",
    title: "Designer",
    balance: 1200,
    status: "None",
    registerDate: "2023-12-20 11:11:55",
    paymentTime: "2024-01-02",
  },
];

// mockData.js
export const mockCardData = [
  {
    id: 1,
    title: "Balans",
    value: "$540",
    icon: <Wallet className="w-5 h-5" />,
    backgroundColor: "bg-blue-500",
  },
  {
    id: 2,
    title: "Tarmoq foydalanuvchilari kamligi",
    value: "0",
    icon: <Users className="w-5 h-5" />,
    backgroundColor: "bg-emerald-500",
  },
  {
    id: 3,
    title: "Bonus summasi",
    value: "$305",
    icon: <Coins className="w-5 h-5" />,
    backgroundColor: "bg-purple-500",
  },
  {
    id: 4,
    title: "Sarlavha",
    value: "AAA",
    icon: <Crown className="w-5 h-5" />,
    backgroundColor: "bg-transparent",
  },
  {
    id: 5,
    title: "Faol diapazon",
    value: "BBB",
    icon: <Wallet className="w-5 h-5" />,
    backgroundColor: "bg-transparent",
  },
  {
    id: 6,
    title: "Bonus summasi",
    value: "$123456",
    icon: <Coins className="w-5 h-5" />,
    backgroundColor: "bg-transparent",
  },
];

export const transactions = [
  {
    id: 1,
    amount: "$10",
    status: "Qaytarildi",
    date: "2025-01-05 18:37:17",
    type: "returned",
  },
  {
    id: 2,
    amount: "$10",
    status: "To'langan",
    date: "2025-01-05 18:36:28",
    type: "paid",
  },
  {
    id: 3,
    amount: "$10",
    status: "To'lanmagan",
    date: "2024-07-11 22:51:18",
    type: "unpaid",
  },
  {
    id: 4,
    amount: "$180",
    status: "To'lanmagan",
    date: "2024-02-14 07:53:34",
    type: "unpaid",
  },
  {
    id: 5,
    amount: "$60",
    status: "To'lanmagan",
    date: "2023-12-16 17:06:38",
    type: "unpaid",
  },
  {
    id: 6,
    amount: "$10",
    status: "To'lanmagan",
    date: "2023-12-16 17:06:07",
    type: "unpaid",
  },
  {
    id: 7,
    amount: "$10",
    status: "To'lanmagan",
    date: "2023-12-16 17:05:52",
    type: "unpaid",
  },
  {
    id: 8,
    amount: "$12",
    status: "To'lanmagan",
    date: "2023-12-16 16:38:45",
    type: "unpaid",
  },
  {
    id: 9,
    amount: "$10",
    status: "To'lanmagan",
    date: "2023-12-16 15:52:48",
    type: "unpaid",
  },
];
