import { clsx } from "clsx";
import { Coins, Users, Wallet } from "lucide-react";
import { twMerge } from "tailwind-merge";

export function cn(...inputs) {
  return twMerge(clsx(inputs));
}

export const baseImageUrl = "http://localhost:8080/uploads/";

export const data = [
  {
    id: 1,
    fullName: "ABCD",
    title: "Менеджер",
    personalPartners: "0 ta",
    activeRange: "1 Month",
    lowNumberOfNetworkUsers: "15",
    bonusAmount: "Саъхат",
  },
  {
    id: 2,
    fullName: "ABCD",
    title: "Бронза",
    personalPartners: "3 ta",
    activeRange: "2 Month",
    lowNumberOfNetworkUsers: "50",
    bonusAmount: "Оилавий саёхат",
  },
  {
    id: 3,
    fullName: "ABCD",
    title: "Серебро",
    personalPartners: "5 ta",
    activeRange: "3 Month",
    lowNumberOfNetworkUsers: "150",
    bonusAmount: "10000 $",
  },
  {
    id: 4,
    fullName: "ABCD",
    title: "Золото",
    personalPartners: "3 ta Менеджер",
    activeRange: "3 Month",
    lowNumberOfNetworkUsers: "300",
    bonusAmount: "20000 $",
  },
  {
    id: 5,
    fullName: "ABCD",
    title: "Платина",
    personalPartners: "2 ta Бронза",
    activeRange: "4 Month",
    lowNumberOfNetworkUsers: "500",
    bonusAmount: "50000 $",
  },
  {
    id: 6,
    fullName: "ABCD",
    title: "Рубин",
    personalPartners: "4 ta Серебро",
    activeRange: "4 Month",
    lowNumberOfNetworkUsers: "1500",
    bonusAmount: "100000 $",
  },
  {
    id: 7,
    fullName: "ABCD",
    title: "Изумруд",
    personalPartners: "3 ta Золото",
    activeRange: "5 Month",
    lowNumberOfNetworkUsers: "3000",
    bonusAmount: "250000 $",
  },
  {
    id: 8,
    fullName: "ABCD",
    title: "Бриллиант",
    personalPartners: "4 ta Платина",
    activeRange: "6 Month",
    lowNumberOfNetworkUsers: "5000",
    bonusAmount: "500000 $",
  },
  {
    id: 9,
    fullName: "ABCD",
    title: "Мерос",
    personalPartners: "4 ta Изумруд",
    activeRange: "6 Month",
    lowNumberOfNetworkUsers: "10000",
    bonusAmount: "1000000 $",
  },
];

// mockData.js
export const mockCardData = [
  {
    id: 1,
    title: "Umumiy Foydalanuvchilar",
    value: "12345",
    icon: <Wallet className="w-5 h-5" />,
    backgroundColor: "bg-blue-500",
  },
  {
    id: 2,
    title: "Aktiv Foydalanuvchilar soni",
    value: "12345",
    icon: <Users className="w-5 h-5" />,
    backgroundColor: "bg-green-500",
  },
  {
    id: 3,
    title: "NoAktiv Foydalanuvchilar soni",
    value: "12345",
    icon: <Coins className="w-5 h-5" />,
    backgroundColor: "bg-purple-500",
  },
];

export const usersData = [
  {
    id: "1",
    first_name: "John",
    last_name: "Doe",
    phone_number: "+1234567890",
    role: "user",
    third_name: "Smith",
    inn: "123456789012",
    email: "john.doe@example.com",
    password: "securepassword123",
    sponsor_id: "someSponsorId",
    parent_id: null,
    passport: "ABC1234567",
    passport_issued: "2024-01-01T00:00:00Z",
    passport_whom_by: "Some Authority",
    left_id: null,
    right_id: null,
    parents: [],
    children: [],
    country: "Uzbekistan",
    degree_id: null,
    register_id: "UZ1234567",
    is_active: true,
    left_pv: 0,
    right_pv: 0,
    mb: 0,
    balance: 1000,
  },
  {
    id: "2",
    first_name: "Alice",
    last_name: "Johnson",
    phone_number: "+9876543210",
    role: "user",
    third_name: "Brown",
    inn: "987654321098",
    email: "alice.johnson@example.com",
    password: "securepassword456",
    sponsor_id: "someOtherSponsorId",
    parent_id: null,
    passport: "XYZ9876543",
    passport_issued: "2023-06-15T00:00:00Z",
    passport_whom_by: "Another Authority",
    left_id: null,
    right_id: null,
    parents: [],
    children: [],
    country: "Uzbekistan",
    degree_id: null,
    register_id: "UZ7654321",
    is_active: false,
    left_pv: 10,
    right_pv: 15,
    mb: 20,
    balance: 500,
  },
  {
    id: "3",
    first_name: "Nodira",
    last_name: "Shonazarova",
    phone_number: "+1234567801",
    role: "admin",
    third_name: "Shonazarova",
    inn: "123987654321",
    email: "nodira.shonazarova@example.com",
    password: "adminpassword123",
    sponsor_id: "adminSponsorId",
    parent_id: null,
    passport: "LMN4567890",
    passport_issued: "2022-09-30T00:00:00Z",
    passport_whom_by: "Admin Authority",
    left_id: null,
    right_id: null,
    parents: [],
    children: [],
    country: "Uzbekistan",
    degree_id: null,
    register_id: "UZ9876543",
    is_active: true,
    left_pv: 50,
    right_pv: 30,
    mb: 40,
    balance: 1500,
  },
  {
    id: "4",
    first_name: "XJ",
    last_name: "Business",
    phone_number: "+1987654321",
    role: "user",
    third_name: "XJ",
    inn: "987123456789",
    email: "xj.business@example.com",
    password: "xjpassword123",
    sponsor_id: "xjSponsorId",
    parent_id: null,
    passport: "OPQ1234567",
    passport_issued: "2021-02-20T00:00:00Z",
    passport_whom_by: "XJ Authority",
    left_id: null,
    right_id: null,
    parents: [],
    children: [],
    country: "Uzbekistan",
    degree_id: null,
    register_id: "UZ0987654",
    is_active: true,
    left_pv: 100,
    right_pv: 50,
    mb: 200,
    balance: 2000,
  },
];
